# Build stage
FROM node:14 AS build
WORKDIR /app

# Copy only package.json and package-lock.json to leverage Docker layer caching
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the Next.js application
RUN npm run build

# Run stage
FROM node:14
WORKDIR /app

# Copy only the built artifacts from the build stage
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/package-lock.json ./package-lock.json

# Expose the port your app runs on
EXPOSE 5000

# Command to run the application
CMD ["npm", "run", "start"]
