name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
    - name: ListFile in directory
      run: ls -l
    - name: Build the Docker image
      run: docker build -t saphalpantha/saphalpantha -f DockerFile .
    - name: Publish image to Docker Hub
      run: docker push saphalpantha/saphalpantha:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
    - name: Pull image from Docker Hub
      run: docker pull saphalpantha/saphalpantha:latest
    - name: Delete old container
      run: docker rm -f saphalpantha-container
    - name: Run Docker Container
      run: docker run -d -p 5000:5000 --name saphalpantha-container saphalpantha/saphalpantha
