name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build Project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build


    deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'ref/heads/main'
      
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: production-files
            path: ./build
          
  


        
        

      
